//! Token-budgeted conversation compaction — the context-continuity layer.
//!
//! A long chat must not silently drop its early turns to stay within the base's
//! context window. Instead of a blunt FIFO that throws away the oldest messages,
//! this module folds the OLDER turns into ONE **structured** summary —
//! intent / goal, files + code touched, key decisions, errors + fixes, pending
//! tasks, current work — generated by a single read-only `complete()` on a
//! FORKED base session (tools denied in spirit: it is a one-shot completion asked
//! only for prose, never an agentic tool loop). The RECENT tail is kept verbatim,
//! so the base sees `[structured summary of earlier work] + [recent verbatim
//! tail]` and keeps continuity instead of being re-primed from cold.
//!
//! Everything here is **deterministic except the summary text itself**: the
//! trigger ([`plan`]), the size caps, the fail-open path, and the circuit breaker
//! ([`Breaker`]) are pure control flow; only the summary body comes from the
//! borrowed brain. Fail-open by contract: a failed / empty / offline summary call
//! yields `None`, which is the caller's signal to fall back to a bounded FIFO drop
//! — it NEVER loses or corrupts the conversation (the full transcript is preserved
//! on disk by the caller, untouched by compaction).

use umadev_runtime::{Message, Runtime};

/// Minimum number of older messages a fold must cover to be worth a base call.
/// A 1-message "fold" is not worth spawning a summary for.
pub const MIN_FOLD: usize = 2;

/// Hard cap (chars) on the rendered folded transcript fed to the summariser, so
/// the summary REQUEST itself can never blow the budget we are reclaiming.
const FOLDED_INPUT_CHARS: usize = 12_000;

/// Hard cap (chars) on the returned summary, so the fold can't reintroduce the
/// bloat it just removed. The summary block stays small and bounded.
pub const SUMMARY_MAX_CHARS: usize = 2_400;

/// `max_tokens` budget for the summary completion (a dense recap, not an essay).
const SUMMARY_MAX_TOKENS: u32 = 900;

/// chars/4 token estimate — the project-wide heuristic (mirrors
/// `director_loop::approx_tokens` and `bounded_transcript`).
fn approx_tokens(s: &str) -> usize {
    s.len() / 4 + 1
}

/// Approximate token cost of a whole transcript (role + content per message).
/// Pure + cheap; the deterministic signal the trigger and tail-window use.
#[must_use]
pub fn transcript_tokens(messages: &[Message]) -> usize {
    messages
        .iter()
        .map(|m| approx_tokens(&m.role) + approx_tokens(&m.content))
        .sum()
}

/// A deterministic compaction decision: fold the leading `fold_count` messages
/// into one summary, keep the remaining (recent) tail verbatim.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub struct CompactionPlan {
    /// How many leading messages to summarise (the older prefix).
    pub fold_count: usize,
}

/// Decide whether — and how much — to compact, **deterministically**.
///
/// Returns `Some(plan)` when the transcript's estimated token cost exceeds
/// `token_budget` AND there are enough older turns to meaningfully fold; `None`
/// otherwise (the caller leaves the conversation untouched).
///
/// The recent tail is always kept verbatim: the newest suffix whose combined cost
/// fits `tail_budget` (but at least `min_tail` messages) stays, and everything
/// before it is the fold. A fold of fewer than [`MIN_FOLD`] messages yields `None`
/// (not worth a base call). For a sane decision pass `tail_budget < token_budget`.
#[must_use]
pub fn plan(
    messages: &[Message],
    token_budget: usize,
    tail_budget: usize,
    min_tail: usize,
) -> Option<CompactionPlan> {
    if transcript_tokens(messages) <= token_budget {
        return None;
    }
    // Keep the newest suffix that fits `tail_budget`, but never fewer than
    // `min_tail` messages (the verbatim recent window).
    let mut tail_len = 0usize;
    let mut est = 0usize;
    for m in messages.iter().rev() {
        let cost = approx_tokens(&m.role) + approx_tokens(&m.content);
        if tail_len >= min_tail && est + cost > tail_budget {
            break;
        }
        est += cost;
        tail_len += 1;
    }
    let tail_len = tail_len.min(messages.len());
    let fold_count = messages.len().saturating_sub(tail_len);
    if fold_count < MIN_FOLD {
        return None;
    }
    Some(CompactionPlan { fold_count })
}

/// Render the folded prefix as a plain `role: content` transcript, oldest →
/// newest, bounded to [`FOLDED_INPUT_CHARS`] so the request stays small. Pure.
fn render_folded(folded: &[Message]) -> String {
    let mut out = String::new();
    for m in folded {
        out.push_str(&m.role);
        out.push_str(": ");
        out.push_str(&m.content);
        out.push_str("\n\n");
    }
    crate::experts::excerpt(out.trim_end(), FOLDED_INPUT_CHARS)
}

/// Build the structured-summary prompt for the folded prefix. The base is asked
/// for a DENSE, factual, multi-section recap (not a paraphrase): intent/goal,
/// files + code touched, key decisions, errors + fixes, pending tasks, current
/// work — the facts a continuing session needs to not lose context. Pure +
/// deterministic, so the prompt shape is unit-tested without opening a base.
#[must_use]
pub fn summary_prompt(folded: &[Message]) -> crate::experts::Prompt {
    let system = "You are compacting the EARLY part of a developer<->assistant coding \
         conversation so it fits the model's context window WITHOUT losing the facts that \
         matter for continuing the work. Produce a DENSE, factual summary under these EXACT \
         section headers, in this order (omit a section ONLY when it is truly empty):\n\
         ## Intent / Goal\n\
         ## Files & code touched\n\
         ## Key decisions\n\
         ## Errors & fixes\n\
         ## Pending tasks\n\
         ## Current work\n\
         Rules: be specific — real file paths, function/type names, concrete decisions and \
         values. Preserve anything the assistant must remember to stay consistent. Do NOT \
         invent facts that aren't in the transcript. No preamble, no closing remarks, no \
         meta-commentary — output ONLY the sections. Write in the conversation's own language."
        .to_string();
    let user = format!(
        "Summarise this earlier conversation for context continuity:\n\n{}",
        render_folded(folded)
    );
    crate::experts::Prompt { system, user }
}

/// Generate the structured summary of `folded` by running ONE read-only
/// `complete()` on `runtime`.
///
/// The caller passes a **fork** (a fresh, no-resume session — see
/// [`Runtime::fork`] / a freshly built brain) so this never touches the live chat
/// session, and the call is a single non-agentic completion (tools denied: it is
/// asked only for prose).
///
/// Returns the cleaned, size-capped summary, or `None` when the runtime is
/// offline, the folded set is below [`MIN_FOLD`], the call errors, or the reply is
/// empty. **Every `None` is the caller's fail-open signal** to fall back to a
/// bounded FIFO drop — it never throws.
pub async fn summarize(runtime: &dyn Runtime, folded: &[Message]) -> Option<String> {
    if runtime.is_offline() || folded.len() < MIN_FOLD {
        return None;
    }
    let prompt = summary_prompt(folded);
    let resp = runtime
        .complete(prompt.into_request(String::new(), SUMMARY_MAX_TOKENS))
        .await
        .ok()?;
    let text = resp.text.trim();
    if text.is_empty() {
        return None;
    }
    Some(crate::experts::excerpt(text, SUMMARY_MAX_CHARS))
}

/// A consecutive-failure circuit breaker for the summary call.
///
/// After [`Breaker::LIMIT`] consecutive failures the breaker **trips** and the
/// caller stops attempting auto-compaction (it relies on the deterministic FIFO
/// floor instead) until a later success resets it. Bounds wasted base calls when
/// the base is down or persistently failing. Deterministic + cheap.
#[derive(Debug, Clone)]
pub struct Breaker {
    consecutive: u32,
    limit: u32,
}

impl Breaker {
    /// Consecutive failures that trip the breaker.
    pub const LIMIT: u32 = 3;

    /// A fresh, untripped breaker.
    #[must_use]
    pub fn new() -> Self {
        Self {
            consecutive: 0,
            limit: Self::LIMIT,
        }
    }

    /// `true` once [`Self::LIMIT`] consecutive failures have been recorded — the
    /// caller should stop attempting auto-compaction until a success resets it.
    #[must_use]
    pub fn tripped(&self) -> bool {
        self.consecutive >= self.limit
    }

    /// Record a successful summary — resets the failure streak (and un-trips).
    pub fn record_success(&mut self) {
        self.consecutive = 0;
    }

    /// Record a failed summary — advances the streak toward [`Self::tripped`].
    pub fn record_failure(&mut self) {
        self.consecutive = self.consecutive.saturating_add(1);
    }
}

impl Default for Breaker {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use async_trait::async_trait;
    use umadev_runtime::{CompletionRequest, CompletionResponse, RuntimeError, RuntimeKind, Usage};

    fn msg(role: &str, content: &str) -> Message {
        Message {
            role: role.to_string(),
            content: content.to_string(),
        }
    }

    /// A fake brain that returns a fixed body (or an error / empty), so the
    /// summary seam is exercised without a real base subprocess.
    struct FakeBrain {
        reply: Option<&'static str>,
        offline: bool,
    }
    #[async_trait]
    impl Runtime for FakeBrain {
        fn kind(&self) -> RuntimeKind {
            RuntimeKind::Anthropic
        }
        fn is_offline(&self) -> bool {
            self.offline
        }
        async fn complete(
            &self,
            _req: CompletionRequest,
        ) -> Result<CompletionResponse, RuntimeError> {
            match self.reply {
                Some(text) => Ok(CompletionResponse {
                    text: text.to_string(),
                    id: "f".into(),
                    model: "f".into(),
                    usage: Usage::default(),
                }),
                None => Err(RuntimeError::HostProcess("boom".into())),
            }
        }
    }

    fn long_convo(n: usize) -> Vec<Message> {
        let mut v = Vec::new();
        for i in 0..n {
            v.push(msg(
                "user",
                &format!("user message number {i} with some length to it"),
            ));
            v.push(msg(
                "assistant",
                &format!("assistant reply number {i} that is also reasonably long padding"),
            ));
        }
        v
    }

    #[test]
    fn plan_is_none_below_budget() {
        let convo = long_convo(2);
        // A generous budget → nothing to compact.
        assert!(plan(&convo, 100_000, 1_000, 4).is_none());
    }

    #[test]
    fn plan_folds_prefix_and_keeps_tail_when_over_budget() {
        let convo = long_convo(20); // 40 messages
        let p = plan(&convo, 200, 80, 4).expect("over budget → some plan");
        // Something is folded, and the tail (>= min_tail) is kept verbatim.
        assert!(p.fold_count >= MIN_FOLD);
        assert!(p.fold_count < convo.len(), "the tail must survive");
        let tail = convo.len() - p.fold_count;
        assert!(
            tail >= 4,
            "at least min_tail messages kept verbatim: {tail}"
        );
    }

    #[test]
    fn plan_respects_min_fold() {
        // Just barely over budget with a big tail window → not enough to fold.
        let convo = long_convo(3); // 6 messages
        assert!(plan(&convo, 1, 100_000, 6).is_none());
    }

    #[test]
    fn summary_prompt_has_every_section() {
        let p = summary_prompt(&long_convo(3));
        for h in [
            "Intent / Goal",
            "Files & code touched",
            "Key decisions",
            "Errors & fixes",
            "Pending tasks",
            "Current work",
        ] {
            assert!(p.system.contains(h), "missing section header: {h}");
        }
        // The folded transcript is carried in the user body.
        assert!(p.user.contains("user message number 0"));
    }

    #[tokio::test]
    async fn summarize_returns_structured_text_on_success() {
        let brain = FakeBrain {
            reply: Some("## Intent / Goal\nBuild a kanban board.\n## Current work\nWiring API."),
            offline: false,
        };
        let out = summarize(&brain, &long_convo(4))
            .await
            .expect("some summary");
        assert!(out.contains("Intent / Goal"));
    }

    #[tokio::test]
    async fn summarize_is_none_on_error_empty_and_offline() {
        // Call error → None (fail-open).
        let err = FakeBrain {
            reply: None,
            offline: false,
        };
        assert!(summarize(&err, &long_convo(4)).await.is_none());
        // Empty reply → None.
        let empty = FakeBrain {
            reply: Some("   "),
            offline: false,
        };
        assert!(summarize(&empty, &long_convo(4)).await.is_none());
        // Offline runtime → None (never even calls).
        let off = FakeBrain {
            reply: Some("x"),
            offline: true,
        };
        assert!(summarize(&off, &long_convo(4)).await.is_none());
    }

    #[tokio::test]
    async fn summarize_is_capped_in_size() {
        let huge: &'static str = Box::leak(
            "## Intent / Goal\n"
                .to_string()
                .repeat(2_000)
                .into_boxed_str(),
        );
        let brain = FakeBrain {
            reply: Some(huge),
            offline: false,
        };
        let out = summarize(&brain, &long_convo(4)).await.unwrap();
        assert!(
            out.chars().count() <= SUMMARY_MAX_CHARS,
            "summary stays bounded"
        );
    }

    #[test]
    fn breaker_trips_after_limit_and_resets_on_success() {
        let mut b = Breaker::new();
        assert!(!b.tripped());
        for _ in 0..Breaker::LIMIT {
            b.record_failure();
        }
        assert!(b.tripped(), "trips after LIMIT consecutive failures");
        b.record_success();
        assert!(!b.tripped(), "a success un-trips the breaker");
    }
}
