//! Spec manifest (`umadev.yaml`) — implements `UD-META-001`.
//!
//! Every conformant UmaDev workspace MUST carry a top-level
//! `umadev.yaml` declaring its spec conformance level. This module
//! defines the file's shape, writes a fresh manifest, and reads back
//! the fields the CLI / doctor care about.
//!
//! Format (canonical, per spec §8.1):
//!
//! ```yaml
//! spec:
//!   version: UMADEV_HOST_SPEC_V1
//!   level: L3
//!   profile: standard
//!   declared_by: umadev@4.4.0
//! project:
//!   slug: <project-slug>
//! quality_gate:
//!   threshold: 90
//! ```
//!
//! The format is deliberately a flat YAML subset so we can hand-roll
//! ser/des and avoid adding a yaml dependency to the workspace.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use umadev_spec::SPEC_VERSION;

/// Filename relative to the workspace root.
pub const MANIFEST_FILENAME: &str = "umadev.yaml";

/// Conformance level the workspace claims.
#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub enum ConformanceLevel {
    /// L1 — Aware (rules visible but advisory).
    L1,
    /// L2 — Enforced (PreToolUse refusals + gates).
    L2,
    /// L3 — Audited (L2 + full evidence chain).
    L3,
}

impl ConformanceLevel {
    /// Canonical string used in the on-disk yaml (`L1` / `L2` / `L3`).
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::L1 => "L1",
            Self::L2 => "L2",
            Self::L3 => "L3",
        }
    }

    /// Parse `L1` / `L2` / `L3` (case-insensitive). `None` otherwise.
    #[must_use]
    pub fn parse(s: &str) -> Option<Self> {
        match s.trim().to_ascii_uppercase().as_str() {
            "L1" => Some(Self::L1),
            "L2" => Some(Self::L2),
            "L3" => Some(Self::L3),
            _ => None,
        }
    }
}

/// Pipeline profile.
#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub enum Profile {
    /// Full 9-phase pipeline.
    Standard,
    /// Competition / time-boxed delivery (alternate phase chain).
    Seeai,
}

impl Profile {
    /// Canonical string used in the on-disk yaml.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Standard => "standard",
            Self::Seeai => "seeai",
        }
    }

    /// Parse `standard` / `seeai` (case-insensitive). `None` otherwise.
    #[must_use]
    pub fn parse(s: &str) -> Option<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "standard" => Some(Self::Standard),
            "seeai" => Some(Self::Seeai),
            _ => None,
        }
    }
}

/// The parsed manifest.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct SpecManifest {
    /// `spec.version` — currently always `UMADEV_HOST_SPEC_V1`.
    pub spec_version: String,
    /// `spec.level` — L1 / L2 / L3.
    pub level: ConformanceLevel,
    /// `spec.profile`.
    pub profile: Profile,
    /// `spec.declared_by` — e.g. `umadev@4.4.0`.
    pub declared_by: String,
    /// `project.slug` (optional).
    pub slug: Option<String>,
    /// `quality_gate.threshold` (defaults to 90).
    pub quality_threshold: u8,
}

impl Default for SpecManifest {
    fn default() -> Self {
        Self {
            spec_version: SPEC_VERSION.to_string(),
            level: ConformanceLevel::L3,
            profile: Profile::Standard,
            declared_by: format!("umadev@{}", env!("CARGO_PKG_VERSION")),
            slug: None,
            quality_threshold: 90,
        }
    }
}

impl SpecManifest {
    /// Build a manifest for a fresh workspace with the given slug.
    #[must_use]
    pub fn new(slug: impl Into<String>) -> Self {
        Self {
            slug: Some(slug.into()),
            ..Self::default()
        }
    }

    /// Render the manifest as canonical YAML text.
    #[must_use]
    pub fn to_yaml(&self) -> String {
        let slug_block = match &self.slug {
            Some(s) => format!("project:\n  slug: {s}\n"),
            None => String::new(),
        };
        format!(
            "# umadev.yaml — UmaDev spec manifest\n\
             # Implements UD-META-001 (UMADEV_HOST_SPEC_V1 §8.1).\n\
             # This file is auto-generated by `umadev init` (or by the first\n\
             # `umadev run` in a workspace). It is safe to edit by hand;\n\
             # `umadev verify` / `umadev doctor` read the fields below.\n\
             \n\
             spec:\n\
             \x20 version: {version}\n\
             \x20 level: {level}\n\
             \x20 profile: {profile}\n\
             \x20 declared_by: {declared_by}\n\
             {slug_block}quality_gate:\n\
             \x20 threshold: {threshold}\n",
            version = self.spec_version,
            level = self.level.as_str(),
            profile = self.profile.as_str(),
            declared_by = self.declared_by,
            threshold = self.quality_threshold,
        )
    }

    /// Read the manifest from the workspace root. `None` if missing or
    /// unreadable; malformed fields fall back to defaults so the value
    /// is always sensible.
    #[must_use]
    pub fn read_from(workspace: &Path) -> Option<Self> {
        let text = fs::read_to_string(workspace.join(MANIFEST_FILENAME)).ok()?;
        Some(parse_manifest(&text))
    }

    /// Write the manifest to `<workspace>/umadev.yaml`. Idempotent
    /// when the content matches; refuses to overwrite a hand-edited
    /// file unless `force` is true and the existing version differs.
    pub fn write_to(&self, workspace: &Path, force: bool) -> io::Result<PathBuf> {
        fs::create_dir_all(workspace)?;
        let path = workspace.join(MANIFEST_FILENAME);
        let body = self.to_yaml();
        if path.is_file() && !force {
            if let Ok(existing) = fs::read_to_string(&path) {
                if existing == body {
                    return Ok(path); // already canonical
                }
                // Don't clobber user edits silently.
                return Err(io::Error::new(
                    io::ErrorKind::AlreadyExists,
                    format!(
                        "{} already exists and differs from the shipped template; \
                         pass --force to overwrite",
                        path.display()
                    ),
                ));
            }
        }
        fs::write(&path, body)?;
        Ok(path)
    }
}

/// Hand-rolled flat YAML parser — only knows about the fields the
/// manifest carries. Anything unrecognised is silently ignored.
fn parse_manifest(text: &str) -> SpecManifest {
    let mut manifest = SpecManifest::default();
    let mut current_section: Option<&str> = None;

    for raw_line in text.lines() {
        let line = strip_comment(raw_line);
        let trimmed = line.trim_end();
        if trimmed.is_empty() {
            continue;
        }
        if !line.starts_with(' ') && !line.starts_with('\t') && line.contains(':') {
            // Top-level key: `spec:`, `project:`, `quality_gate:`
            let key = line.split(':').next().unwrap_or("").trim();
            current_section = match key {
                "spec" => Some("spec"),
                "project" => Some("project"),
                "quality_gate" => Some("quality_gate"),
                _ => None,
            };
            continue;
        }
        // Nested key: `  key: value`
        let kv = line.trim();
        let Some((key, val)) = kv.split_once(':') else {
            continue;
        };
        let key = key.trim();
        let val = val.trim().trim_matches('"').trim_matches('\'');
        match (current_section, key) {
            (Some("spec"), "version") => manifest.spec_version = val.to_string(),
            (Some("spec"), "level") => {
                if let Some(l) = ConformanceLevel::parse(val) {
                    manifest.level = l;
                }
            }
            (Some("spec"), "profile") => {
                if let Some(p) = Profile::parse(val) {
                    manifest.profile = p;
                }
            }
            (Some("spec"), "declared_by") => manifest.declared_by = val.to_string(),
            (Some("project"), "slug") => manifest.slug = Some(val.to_string()),
            (Some("quality_gate"), "threshold") => {
                if let Ok(n) = val.parse::<u8>() {
                    manifest.quality_threshold = n;
                }
            }
            _ => {}
        }
    }
    manifest
}

#[allow(clippy::too_many_lines)]
fn strip_comment(line: &str) -> &str {
    // Strip a YAML trailing comment (`# ...`) but only when the `#` is NOT
    // inside a quoted string. Previously `declared_by: "C# project"` lost
    // everything from `#` onward. Walk the line tracking single/double
    // quotes; the first un-quoted `#` (with whitespace before it, per YAML
    // spec where `#` must be preceded by whitespace to start a comment)
    // begins the comment.
    let mut in_single = false;
    let mut in_double = false;
    let bytes: Vec<char> = line.chars().collect();
    let mut i = 0;
    while i < bytes.len() {
        let c = bytes[i];
        match c {
            '\\' if (in_single || in_double) && i + 1 < bytes.len() => {
                // Escaped char inside a quote — skip the next char.
                i += 2;
                continue;
            }
            '\'' if !in_double => in_single = !in_single,
            '"' if !in_single => in_double = !in_double,
            '#' if !in_single && !in_double => {
                // YAML requires whitespace before `#` for it to be a comment
                // (so `a#b` in an unquoted scalar is literal). Check the
                // preceding non-quoted char.
                let prev_ws = i > 0 && bytes[i - 1].is_whitespace();
                if i == 0 || prev_ws {
                    return line[..char_byte_offset(line, i)].trim_end();
                }
            }
            _ => {}
        }
        i += 1;
    }
    line
}

/// Byte offset of the `char_idx`-th char in `s` (for slicing the original
/// &str after a char-index walk).
fn char_byte_offset(s: &str, char_idx: usize) -> usize {
    s.char_indices()
        .nth(char_idx)
        .map(|(b, _)| b)
        .unwrap_or(s.len())
}

#[cfg(test)]
mod tests {
    #[test]
    fn strip_comment_keeps_hash_in_quotes() {
        // A `#` inside a quoted value is NOT a comment start.
        let line = r#"title: "C# project""#;
        assert_eq!(super::strip_comment(line), line);
        // Unquoted `a#b` (no whitespace before #) is literal per YAML.
        let line2 = "declared_by: a#b";
        assert_eq!(super::strip_comment(line2), line2);
        // A real trailing comment (whitespace before #) is stripped.
        let line3 = "key: value # a comment";
        assert_eq!(super::strip_comment(line3), "key: value");
        // A full-line comment.
        assert_eq!(super::strip_comment("# just a comment"), "");
    }

    use super::*;
    use tempfile::TempDir;

    #[test]
    fn default_manifest_carries_spec_version() {
        let m = SpecManifest::default();
        assert_eq!(m.spec_version, SPEC_VERSION);
        assert_eq!(m.level, ConformanceLevel::L3);
        assert_eq!(m.profile, Profile::Standard);
        assert_eq!(m.quality_threshold, 90);
        assert!(m.declared_by.starts_with("umadev@"));
    }

    #[test]
    fn write_then_read_round_trip() {
        let tmp = TempDir::new().unwrap();
        let m = SpecManifest::new("demo");
        let path = m.write_to(tmp.path(), false).unwrap();
        assert!(path.exists());
        let back = SpecManifest::read_from(tmp.path()).unwrap();
        assert_eq!(back, m);
    }

    #[test]
    fn write_is_idempotent_for_identical_body() {
        let tmp = TempDir::new().unwrap();
        let m = SpecManifest::default();
        m.write_to(tmp.path(), false).unwrap();
        m.write_to(tmp.path(), false).unwrap(); // no error
    }

    #[test]
    fn write_refuses_to_clobber_user_edit() {
        let tmp = TempDir::new().unwrap();
        let m = SpecManifest::default();
        m.write_to(tmp.path(), false).unwrap();
        fs::write(tmp.path().join(MANIFEST_FILENAME), "spec:\n  level: L1\n").unwrap();
        let err = m.write_to(tmp.path(), false).unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::AlreadyExists);
    }

    #[test]
    fn force_overwrites_user_edit() {
        let tmp = TempDir::new().unwrap();
        let m = SpecManifest::default();
        m.write_to(tmp.path(), false).unwrap();
        fs::write(tmp.path().join(MANIFEST_FILENAME), "spec:\n  level: L1\n").unwrap();
        m.write_to(tmp.path(), true).unwrap();
        let back = SpecManifest::read_from(tmp.path()).unwrap();
        assert_eq!(back.level, ConformanceLevel::L3); // back to shipped default
    }

    #[test]
    fn read_extracts_quoted_values() {
        let tmp = TempDir::new().unwrap();
        fs::write(
            tmp.path().join(MANIFEST_FILENAME),
            r#"
spec:
  version: "UMADEV_HOST_SPEC_V1"
  level: 'L2'
  profile: standard
  declared_by: umadev@4.4.0
project:
  slug: my-project
quality_gate:
  threshold: 85
"#,
        )
        .unwrap();
        let m = SpecManifest::read_from(tmp.path()).unwrap();
        assert_eq!(m.spec_version, "UMADEV_HOST_SPEC_V1");
        assert_eq!(m.level, ConformanceLevel::L2);
        assert_eq!(m.slug.as_deref(), Some("my-project"));
        assert_eq!(m.quality_threshold, 85);
    }

    #[test]
    fn read_tolerates_comments_and_blank_lines() {
        let tmp = TempDir::new().unwrap();
        fs::write(
            tmp.path().join(MANIFEST_FILENAME),
            "\
# top comment
spec:
  # spec section comment
  version: UMADEV_HOST_SPEC_V1
  level: L3

  profile: standard  # trailing comment
  declared_by: umadev@4.4.0
",
        )
        .unwrap();
        let m = SpecManifest::read_from(tmp.path()).unwrap();
        assert_eq!(m.spec_version, "UMADEV_HOST_SPEC_V1");
        assert_eq!(m.level, ConformanceLevel::L3);
        assert_eq!(m.profile, Profile::Standard);
    }

    #[test]
    fn read_falls_back_to_defaults_on_unknown_fields() {
        let tmp = TempDir::new().unwrap();
        fs::write(
            tmp.path().join(MANIFEST_FILENAME),
            "spec:\n  level: nope\n  profile: bogus\n",
        )
        .unwrap();
        let m = SpecManifest::read_from(tmp.path()).unwrap();
        assert_eq!(m.level, ConformanceLevel::L3);
        assert_eq!(m.profile, Profile::Standard);
    }

    #[test]
    fn read_returns_none_when_missing() {
        let tmp = TempDir::new().unwrap();
        assert!(SpecManifest::read_from(tmp.path()).is_none());
    }

    #[test]
    fn yaml_renders_all_required_fields() {
        let m = SpecManifest::new("acme-app");
        let y = m.to_yaml();
        assert!(y.contains("version: UMADEV_HOST_SPEC_V1"));
        assert!(y.contains("level: L3"));
        assert!(y.contains("profile: standard"));
        assert!(y.contains("declared_by: umadev@"));
        assert!(y.contains("slug: acme-app"));
        assert!(y.contains("threshold: 90"));
    }
}
